### ISSUE TITLE
Table size breakdown should include schema names

### ISSUE THREAD

**Issue by lizztheblizz** [planetscale/ps-prechecks#3]
Currently, in situations where we have multiple schemas in MySQL, it's not easy to identify at a glance where those tables live. Let's adjust the queries and report to include that info.
```[tasklist]
### Tasks
- [x] Change underlying query
- [x] Adjust report display
```

**Comment by jonahberquist** [comment]
Fixed by https://github.com/planetscale/ps-prechecks/pull/4
